[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config._ = {
      \ 'runner'    : 'vimproc',
      \ 'runner/vimproc/updatetime' : 60,
      \ 'outputter' : 'error',
      \ 'outputter/error/success' : 'buffer',
      \ 'outputter/error/error'   : 'quickfix',
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
    # 以下、hook_addで設定している項目上から
    # タブラインの表示
    # （タブが一個の場合）バッファのリストをタブラインに表示する機能をオフ
    # 0でそのタブで開いてるウィンドウ数、1で左のタブから連番
    # パワーラインフォントの使用
    # aleの表示
    # Do not collapse the status line while having multiple windows
    # tagbarの表示
    # virtualenvを有効
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#show_buffers = 1
    let g:airline#extensions#tabline#tab_nr_type = 1
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#ale#enabled = 1
    let g:airline_inactive_collapse = 1
    let g:airline#extensions#tagbar#enabled = 1
    let g:airline#extensions#virtualenv#enabled = 1
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
    let g:cheatsheet#cheat_file = '~/.config/nvim/.cheatsheet.md'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=500
  let g:gitgutter_highlight_lines = 1
'''

# git statusで*.swpを無視したい場合、作業ディレクトリに.gitignoreファイルを追加し、*.swpを記述
[[plugins]]
repo = 'tpope/vim-fugitive'
